# based on https://github.com/shuntaka9576/dotfiles

# enable display 256 color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# tmux utils
bind -n M-t choose-tree -Z -O name
bind -n M-s choose-session -Z -O name
bind -n M-w choose-tree -w -Z -O name

# highlight the selected line (cursor) in choose-* / copy-mode
set -g mode-style "bg=#82aaff,fg=colour255,bold"

# operate windows settings
set -s escape-time 0
set -g renumber-windows on
bind -n M-n new-window -c "#{pane_current_path}"
bind -n M-. next-window
bind -n M-, previous-window
bind -n M-> swap-window -d -t +1
bind -n M-< swap-window -d -t -1
bind -n M-r command-prompt "rename-window -- '%%'"

bind -n M-N command-prompt "new-session -n '%1'"

# split window settings
bind -n M-/ split-window -h -c "#{pane_current_path}" # Conflict vim to setting Ctrl
bind -n M-- split-window -v -c "#{pane_current_path}"

bind -n M-i kill-window

# popup (tmux-file-picker)
bind -n C-f display-popup -E -d "#{pane_current_path}" -w 90% -h 90% "tmux-file-picker"

# enable operate mouse
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# change prefix
set -g prefix C-k
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind -T copy-mode-vi Y send -X copy-line

# resize pein config
bind -n M-H resize-pane -L 10
bind -n M-J resize-pane -D 10
bind -n M-K resize-pane -U 10
bind -n M-L resize-pane -R 10

# tmux-navigator settings
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n M-h if-shell "$is_vim" "send-keys C-w h"  "select-pane -L"
bind -n M-j if-shell "$is_vim" "send-keys C-w j"  "select-pane -D"
bind -n M-k if-shell "$is_vim" "send-keys C-w k"  "select-pane -U"
bind -n M-l if-shell "$is_vim" "send-keys C-w l"  "select-pane -R"
# bind \ if-shell "$is_vim" "send-keys C-w \\" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
# bind-key -T copy-mode-vi C-\ select-pane -l

# powerline
set-option -g status-position top
set-option -g status-interval 1 # update interval
set-option -g status-bg "colour238" # background color
set-option -g status-fg "colour255" # status line color
set-window-option -g window-status-current-format "#[fg=colour255,bg=#82aaff,bold] #W #[default]"
set-window-option -g window-status-format "#[fg=colour145,bold] #W #[default]"
set -g status-right "%m/%d %H:%M"
# set-option -g status-right-length 80
# set-option -g status-right "#(~/dotfiles/tmux/powerline/battery)#[fg=colour117, bold]%H:%M:%S %m/%d #[default]#(~/dotfiles/tmux/powerline/ssid)#(~/dotfiles/tmux/powerline/sound)"
# set-option -g status-right "#(~/dotfiles/tmux/powerline/battery)#[fg=colour117, bold]%H:%M:%S %m/%d #[default]#(~/dotfiles/tmux/powerline/ssid)"
set -g status-left "#[fg=colour145,bold][#S] "

# emphasize pane border
set -g pane-border-style "fg=colour245"
set -g pane-active-border-style "fg=green,bold"
set -g pane-border-lines heavy
