keys:
  - &terra age1uu5ar4m7263x2phv87cdc6cpzfrrc48tzvgeh63g8qkyumjxlcqq2evl40
  - &rhine age1m2vffs0vwclra86gf2kwxgylf7zqumup50ma7npnp6sld4qd6p3sxukl4v
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *terra
          - *rhine
