name: Update dotfiles flake input
description: Submit a PR to asa1984/dotfiles to update a flake input

inputs:
  input:
    description: "The flake input to update"
    required: true
  token:
    description: "The GitHub token to use for authentication"
    required: true
  base:
    description: "The base branch to create the PR against"
    required: false
    default: "main"
  title:
    description: "The commit title"
    required: true
  body:
    description: "The commit body"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: asa1984/dotfiles
        token: ${{ inputs.token }}
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        set +e
        set +o pipefail

        git config --global user.name github-actions[bot]
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com


        nix flake update "${{ inputs.input }}"

        branch="update-flake-input/${{ inputs.input }}"
        git switch -c "$branch" 
        git commit --all --message "${{ inputs.title }}" --message "${{ inputs.body }}"
        git push --force origin "$branch"
        gh pr create --fill --base "${{ inputs.base }}"
        gh pr merge --auto --squash --delete-branch
