{pkgs, ...}: let
  # TODO: add a way to change the wallpaper
  wallpaper = "silent_sea";
in {
  imports = [
    ./rofi
    ./dunst.nix
  ];

  xsession = {
    enable = true;
    scriptPath = ".hm-xsession";
    windowManager.xmonad = {
      enable = true;
      enableContribAndExtras = true;
      config = ./config.hs;
      extraPackages = haskellPackages:
        with haskellPackages; [xmonad-contrib xmonad-extras lens data-default];
    };
  };

  home.packages = with pkgs; [
    arandr # xrandr gui
    brightnessctl # brightness control
    feh # wallpaper
    maim # screenshot
    playerctl # media control
    xclip # clipboard
  ];

  # ~/.hm_desktop is a directory for desktop files generated by home-manager
  home.file = {
    "xrandr.sh" = {
      target = ".hm_desktop/xrandr.sh";
      source = ./script/dual_monitor.sh;
    };
    "wallpaper.jpg" = {
      target = ".hm_desktop/wallpaper.jpg";
      source = ./wallpaper/${wallpaper}.jpg;
    };
    "screenshot.sh" = {
      target = ".hm_desktop/screenshot.sh";
      source = ./script/screenshot.sh;
    };
    "snipping_tool.sh" = {
      target = ".hm_desktop/snipping_tool.sh";
      source = ./script/snipping_tool.sh;
    };
  };
}
