{pkgs, ...}: {
  imports = [
    ./rofi
    ./dunst.nix
  ];

  xsession = {
    enable = true;
    scriptPath = ".hm-xsession";
    windowManager.xmonad = {
      enable = true;
      enableContribAndExtras = true;
      config = ./config.hs;
      extraPackages = haskellPackages:
        with haskellPackages; [xmonad-contrib xmonad-extras lens data-default];
    };
  };

  home.packages = with pkgs; [
    arandr # xrandr gui
    brightnessctl # brightness control
    feh # wallpaper
    maim # screenshot
    playerctl # media control
    xclip # clipboard
    xcolor # color picker
  ];

  # ~/.hm_desktop is a directory for desktop files generated by home-manager
  home.file = {
    "xrandr.sh" = {
      target = ".hm_desktop/xrandr.sh";
      source = ./script/dual_monitor.sh;
    };
    "wallpaper.jpg" = {
      target = ".hm_desktop/wallpaper.jpg";
      source = pkgs.fetchurl {
        url = "https://i.redd.it/49mj5c88ndla1.jpg";
        sha256 = "sha256-idMl5YkMMrXfBW36eG0buuJZ1IjmZLG/5TwfVROmC2s=";
      };
    };
    "screenshot.sh" = {
      target = ".hm_desktop/screenshot.sh";
      source = ./script/screenshot.sh;
    };
    "snipping_tool.sh" = {
      target = ".hm_desktop/snipping_tool.sh";
      source = ./script/snipping_tool.sh;
    };
  };
}
