{
  inputs,
  pkgs,
  lib,
  config,
  username,
  ...
}:
{
  imports =
    [
      ./hardware-configuration.nix

      ../../configs/nixos/core/docker.nix
      ../../configs/nixos/core/network.nix
      ../../configs/nixos/core/nix.nix
      ../../configs/nixos/core/shell.nix

      ../../configs/nixos/apps/keybase.nix
      ../../configs/nixos/apps/keyring.nix
      ../../configs/nixos/apps/sops.nix
      ../../configs/nixos/apps/sunshine.nix
      ../../configs/nixos/apps/tailscale.nix
      ../../configs/nixos/apps/xremap.nix

      ../../configs/nixos/desktop/fcitx5.nix
      ../../configs/nixos/desktop/fonts.nix
      ../../configs/nixos/desktop/hyprland.nix
      ../../configs/nixos/desktop/sound.nix
    ]
    ++ (with inputs.nixos-hardware.nixosModules; [
      common-cpu-amd
      common-gpu-amd
      common-pc-ssd
      common-pc-laptop
    ]);

  # Don't touch this
  system.stateVersion = "22.11";

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot/efi";
      };
    };
    kernelPackages = pkgs.linuxKernel.packages.linux_zen;
  };

  users.users."${username}" = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "networkmanager"
      "wheel"
      "audio"
      "video"
    ];
  };
  time.timeZone = "Asia/Tokyo";
  i18n.defaultLocale = "en_US.UTF-8";

  programs.nix-ld.enable = true;

  # Bluetooth
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # Power management
  services.upower.enable = true;

  # Use session generated by home-manager
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${lib.getExe pkgs.greetd.tuigreet} --cmd ${lib.getExe config.programs.hyprland.package}";
        user = username;
      };
    };
  };
}
