{
  inputs,
  pkgs,
  lib,
  config,
  username,
  ...
}:
{
  imports =
    [
      ./hardware-configuration.nix

      ../../modules/core
      ../../modules/desktop
      ../../modules/programs/flatpak.nix
      ../../modules/programs/hyprland.nix
      ../../modules/programs/keybase.nix
      ../../modules/programs/media.nix
      ../../modules/programs/shell.nix
      ../../modules/programs/steam.nix
    ]
    ++ (with inputs.nixos-hardware.nixosModules; [
      common-cpu-amd
      common-gpu-amd
      common-pc-ssd
      common-pc-laptop
    ]);

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot/efi";
      };
    };
    kernelPackages = pkgs.linuxKernel.packages.linux_zen;
  };

  # Don't touch this
  system.stateVersion = "22.11";

  users.users."${username}" = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "networkmanager"
      "wheel"
      "audio"
      "video"
    ];
  };

  # Bluetooth
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # Power management
  services.upower.enable = true;

  # Use session generated by home-manager
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${lib.getExe pkgs.greetd.tuigreet} --cmd ${lib.getExe config.programs.hyprland.package}";
        user = username;
      };
    };
  };
}
