login-password: ENC[AES256_GCM,data:OhxUK7aNdUyOfcho5O9QGIKVBmLXkHW65V8at0W57eDC+hTL7ZNZPbwGI9V93aonLmP6Vsr4d/WrmLMsT3g10pd4t7l2EeyDBw==,iv:irWEWN3touXk6WyW0ywsA2InvmFWgoke/QBmXVikg9s=,tag:4JTpw84u/4j3CITptCGOkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uu5ar4m7263x2phv87cdc6cpzfrrc48tzvgeh63g8qkyumjxlcqq2evl40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMVdiUjFIMUxzbXhVYnU2
            cElPNWxDS3M1Q25jOStHOXk0aWdVSmUyL1JNCjBxTlB4b2RwcmlVVDA1K0YxT3lL
            V3c4eUY1QmN0ZU5nNUMrRGZ2MkJwaDQKLS0tIGZLZkJrcm9xaGpjYVQzOVpGTTBZ
            dE51V1VxWFVGNm1abTVuUklhWFdpQ28K/z/KUxnfHi1B4J6k7UZuhvwaFdIU0cna
            YsHClCS8LimCLYbOh4L1U8anRmKdR2GI3Onxjf78AOV40ZjkMUW0Sg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m2vffs0vwclra86gf2kwxgylf7zqumup50ma7npnp6sld4qd6p3sxukl4v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY29nWVJEZlg5Ylg4TzFk
            VGtYdEt5TS9STVowV1BOenNiRUtkRmdFTGxvClJKb1EzK0ZrSlBBMVkyVVdCazV4
            OGpJeW15VmJ4THVnTWkzRDFVd2Y1Zk0KLS0tIDZpNCtKeHgwYkliTERJSUhvNzVS
            UVJrRUt1bFRhMlE1eUFxekhGR2NHbUUKK8GLYeIjG7ih9dZN8dyoLB8kcMl4Sm7U
            Y2L6W6zyBUjkjf8YKu6cpS+6oQ+9zoMmqDEqrOEz8lRCYZiixypKjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T06:44:44Z"
    mac: ENC[AES256_GCM,data:LSx1Lc27mElBNPUxPBiYgokNGMrB0LPJiVB7hqr0hESeX5ObRUCkSVUC6VORSorAkZ2kbk9OBSoYVCBg9lRc08PV/Q/PG+t7QwIPS/WXbghs+cbzW4w6ZgmSAuUj1NejmDJJ7Wssr/QH8IZHdkm2lOkI75ikBvTQ+xDrYnfzT8o=,iv:RR8NffykC5DWfhSv6uIo8z+kZzNT4n2QYB1G6qaTJto=,tag:tl7ylQU9YUjVajVL5E7+3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
